django_notebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notebook.urls')),
    path('', include('history.urls'))
]

history/urls.py
from django.urls import path

from history import views

urlpatterns = [
    path('delete/<int:pk>', views.HistoryDelete.as_view(), name='history_delete'),
    path('', views.HistoryList.as_view(), name='history'),
]

notebook/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import (NoteHomepageView, validate_new_note_view, NoteUpdateView, tabbed_view,
                    delete_note_view, upload_image, note_history, note_version)

app_name = 'notes'

urlpatterns = [

    path('', NoteHomepageView.as_view(), name='home'),
    path('tabbed/<int:pk>/', tabbed_view, name='tabbed'),
    path('validate-note-creation/', validate_new_note_view, name='validate_note_creation'),
    path('note/update/<int:notebooktab_id>/<uuid:pk>/', NoteUpdateView.as_view(), name='note_update'),
    path('note/delete/<uuid:pk>/', delete_note_view, name="delete_note"),
    path('view/<uuid:id>/', NoteHomepageView.as_view(), name="id"),
    path('notebook/<int:notebook_id>/', NoteHomepageView.as_view(), name="notebook_id"),
    path('notebook/tab/<int:notebooktab_id>/', NoteHomepageView.as_view(), name="tab"),
    path('notebook/tab/<int:notebooktab_id>/note/<uuid:note_id>', NoteHomepageView.as_view(), name='note'),

    # Revisions / Versioning
    path('api/note/<uuid:note_id>/history/', note_history, name='note_history'),
    path('api/note/version/<int:version_id>/', note_version, name='note_version'),

    # Upload pictures
    path('upload_image/', upload_image),

    # Tinymce editor
    path('tinymce/', include('tinymce.urls')),

    # Search
    path('search/', NoteHomepageView.as_view(), name='search')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notebook/models.py
import uuid
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField

COLORS = (
        ('a', 'yellow'),
        ('b', 'white'),
        ('c', 'green'),
        ('d', 'red'),
        ('e', 'blue')
    )


class Tags(models.Model):
    title = models.CharField(unique=True, max_length=240)

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('notes:tag_update', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('notes:tag_delete', kwargs={'pk': self.id})

    @staticmethod
    def filters_data(request, qs):
        q = request.GET.get('q', None)
        search_name = request.GET.get('search_name', None)

        qs = qs.filter(title__icontains=q) if q else qs
        qs = qs.filter(title__icontains=search_name) if search_name else qs
        return qs




class Notebook(models.Model):

    title = models.CharField(max_length=400)
    description = HTMLField(blank=True)
    color = models.CharField(max_length=1, choices=COLORS, default='a')

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('notes:notebook_update', kwargs={'pk': self.id})

    # @staticmethod
    # def filters_data(request, qs):
    #     q = request.GET.get('q', None)
    #     tags = request.GET.getlist('tag', None)
    #     if tags:
    #         tags_ = Tags.objects.filter(id__in=tags)
    #         qs = qs.filter(tag__in=tags_)
    #     qs = qs.filter(title__icontains=q) if q else qs
    #     return qs

class NotebookTab(models.Model):

    title = models.CharField(max_length=400)
    description = HTMLField(blank=True)
    color = models.CharField(max_length=1, choices=COLORS, default='a')

    notebook = models.ForeignKey(Notebook, on_delete=models.CASCADE, related_name='children')

    class Meta:
        ordering = ['notebook_id']

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('notes:notebooktab_update', kwargs={'pk': self.id})



class Note(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    title = models.CharField(max_length=400)
    description = HTMLField(blank=True)

    created_timestamp = models.DateTimeField(auto_now_add=True)
    modified_timestamp = models.DateTimeField(auto_now=True)

    indent = models.SmallIntegerField(default=4, editable=False)
    notebooktab = models.ForeignKey(NotebookTab, on_delete=models.CASCADE)
    display_order = models.IntegerField(default=0, editable=False)
    class Meta:
        ordering = ['display_order']

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('notes:note_update', kwargs={'pk': self.id, 'notebooktab_id': self.notebooktab_id})

    @staticmethod
    def filters_data(request, qs):
        q = request.GET.get('q', None)
        # tags = request.GET.getlist('tag', None)
        # if tags:
        #     tags_ = Tags.objects.filter(id__in=tags)
        #     qs = qs.filter(tag__in=tags_)
        qs = qs.filter(title__icontains=q) if q else qs
        return qs

notebook/forms.py
from django import forms
from .fields import GroupedModelChoiceField
from .models import Note, Notebook, NotebookTab


class BaseForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class NoteForm(BaseForm, forms.ModelForm):

    notebooktab = GroupedModelChoiceField(
        queryset=NotebookTab.objects.exclude(notebook=None),
        choices_groupby='notebook'
    )

    class Meta:
        model = Note
        fields = ['notebooktab', 'title', 'description']


# class TagForm(BaseForm, forms.ModelForm):

#     class Meta:
#         model = Tags
#         fields = '__all__'

notebook/views.py
import os

from rest_framework.decorators import api_view
from rest_framework.response import Response
from reversion.models import Version
from django.db.models import F

from django.shortcuts import reverse, redirect, get_object_or_404, HttpResponseRedirect, render
from django.urls import reverse_lazy
from django.conf import settings
from django.http import JsonResponse
from django.utils import timezone
from django.views.generic import ListView, UpdateView, DetailView, CreateView
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages

from django_tables2 import RequestConfig

from .models import Tags, Note, Notebook, NotebookTab
from .forms import NoteForm
from history.signals import object_viewed_signal
#from .tables import TagsTable


#@method_decorator(staff_member_required, name='dispatch')
class NoteHomepageView(ListView):

    template_name = 'notes/homepage.html'
    model = Note

    def get_queryset(self):

        qs_notes = Note.objects.all()

        note_id = ''

        if 'id' in self.kwargs:
            id = self.kwargs['id']
            qs_notes = [Note.objects.all().filter(id=id)]
            if self.request.user.is_authenticated and self.get_object() is not None:
                object_viewed_signal.send(self.get_object().__class__, instance=self.get_object(), request=self.request)

        elif 'notebook_id' in self.kwargs:
            notebook_id = self.kwargs['notebook_id']
            qs_notes = [Note.objects.all().filter(id=notebook_id)]

        elif 'notebooktab_id' in self.kwargs:

            # We are on a tab, find out which one here
            notebooktab_id = self.kwargs['notebooktab_id']

            # Get all the notes for the tab
            qs_notes = Note.objects.all().filter(notebooktab_id=notebooktab_id)

            # Are we viewing a specific note?
            if 'note_id' in self.kwargs:
                note_id = self.kwargs['note_id']

                the_note_object =  Note.objects.all().filter(id=note_id)[0]

                if self.request.user.is_authenticated and the_note_object is not None:
                    object_viewed_signal.send(the_note_object.__class__, instance=the_note_object, request=self.request)

            else:

                # Get the note id of the first note
                if len(qs_notes) > 0:
                    note_id = qs_notes[0].id

        else:
            qs_notes = Note.filters_data(self.request, qs_notes)
            qs_notes = []

        qs_notebooks = Notebook.objects.all()

        qs_notebooks_and_tabs = Notebook.objects.all().select_related()

        return qs_notes, qs_notebooks, qs_notebooks_and_tabs, note_id

    def get_context_data(self,**kwargs):

        context = super().get_context_data(**kwargs)

        notebooktab_id = ''
        if 'notebooktab_id' in self.kwargs:
            notebooktab_id = self.kwargs['notebooktab_id']
            context['notebooktab_id'] = notebooktab_id

        context['create_form'] = NoteForm(initial ={'notebooktab': notebooktab_id})

        context['qs'] = self.object_list[0][:30]
        context['notebooks'] = self.object_list[1][:30]
        context['notebooks_and_tabs'] = self.object_list[2][:30]

        context['note_id'] = self.object_list[3]

        context['action_url'] = '/search/'
        context['q'] = self.request.GET.get('q', None)

        if self.request.path == '/search/':
            qs1 = Note.objects.all().filter(title__icontains=context['q'])
            qs2 = Note.objects.all().filter(description__icontains=context['q'])
            context['qs'] = qs1 | qs2

        return context



#@staff_member_required
def validate_new_note_view(request):
    form = NoteForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'New note added')
    return redirect(reverse('notes:note', args=[form.instance.notebooktab_id, form.instance.id]))


#@method_decorator(staff_member_required, name='dispatch')
class NoteUpdateView(UpdateView):

    form_class = NoteForm

    template_name = 'notes/form.html'
    model = Note

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['back_url'] = reverse_lazy('notes:note', args=[self.object.notebooktab_id, self.object.id])
        context['form_title'] = f'[ MODIFYING ] {self.object.title}'
        return context

    def form_valid(self, form):
        self.success_url = reverse_lazy('notes:note', args=[self.object.notebooktab_id, self.object.id])
        form.save()
        messages.success(self.request, f'The note has been updated')
        return super().form_valid(form)


#@staff_member_required
def tabbed_view(request, pk):
    # instance = get_object_or_404(Note, id=pk)
    # instance.pinned = False if instance.pinned else True
    # instance.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'), reverse('notes:home'))

#@staff_member_required
def tab(request, pk):
    # instance = get_object_or_404(Note, id=pk)
    # instance.pinned = False if instance.pinned else True
    # instance.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'), reverse('notes:home'))

#@staff_member_required
def delete_note_view(request, pk):
    instance = get_object_or_404(Note, id=pk)
    instance.delete()
    messages.warning(request, 'Deleted')
    return redirect(reverse('notes:home'))


@csrf_exempt
def upload_image(request):
    if request.method == "POST":
        file_obj = request.FILES['file']
        file_name_suffix = file_obj.name.split(".")[-1]
        if file_name_suffix not in ["jpg", "png", "gif", "jpeg", ]:
            return JsonResponse({"message": "Wrong file format"})

        upload_time = timezone.now()
        path = os.path.join(
            settings.MEDIA_ROOT,
            'tinymce',
            str(upload_time.year),
            str(upload_time.month),
            str(upload_time.day)
        )
        # If there is no such path, create
        if not os.path.exists(path):
            os.makedirs(path)

        file_path = os.path.join(path, file_obj.name)

        file_url = f'{settings.MEDIA_URL}tinymce/{upload_time.year}/{upload_time.month}/{upload_time.day}/{file_obj.name}'

        if os.path.exists(file_path):
            return JsonResponse({
                "message": "file already exist",
                'location': file_url
            })

        with open(file_path, 'wb+') as f:
            for chunk in file_obj.chunks():
                f.write(chunk)

        return JsonResponse({
            'message': 'Image uploaded successfully',
            'location': file_url
        })
    return JsonResponse({'detail': "Wrong request"})


@api_view()
def note_history(request, note_id):
    note = Note.objects.get(id=note_id)
    versions = Version.objects.get_for_object(note)

    data = versions.values('pk',
                           date_created=F('revision__date_created'),
                           user=F('revision__user__username'),
                           comment=F('revision__comment'))

    return Response({"data": data})

@api_view()
def note_version(request, version_id):
    v = Version.objects.get(id=version_id)
    return Response({"data": v.field_dict})

notebook/templates/notes/form.html
{% extends 'dashboard.html' %} {% load render_table from django_tables2 %}

{% block extra_css %}
{{ form.media }}
<style>
    textarea.form-control {
        max-height: 600px;
        width: 1800px;
    }

    #id_description {
        max-height: 600px;
        height: 600px;
    }

    #id_tag {
        max-height: 250px;
        height: 250px;
    }
</style>
{% endblock %}

{% block content %}
<div class="content">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class='card'>
                <div class='card-header'>
                    <h4>{{form_title}}</h4>
                    <!-- Large modal -->
                    <a href="{{ back_url }}" class="btn btn-warning pull-right">Back</a>
                </div>
                <div class="card-body">
                    <form method='post' class='form'>
                        {% csrf_token %}
                        {{ form }}
                        <br />
                        <button class='btn btn-success pull-right' type='submit'><i class='fa fa-save'></i></button>
                    </form>
                    </card>

                </div>
            </div>
            <div class="col-2"></div>
        </div>


    </div>

</div>

{% endblock %}

notebook/templates/notes/homepage.html
{% extends 'dashboard.html' %} {% load render_table from django_tables2 %}

{% block extra_css %}
{{ create_form.media }}
<style>
    textarea.form-control {
        max-height: 600px;
        width: 1800px;
    }

    #id_description {
        max-height: 500px;
        height: 500px;
    }

    #id_description_ifr {
        max-height: 500px;
        height: 500px;
    }

    #id_tag {
        max-height: 150px;
        height: 150px;
    }
</style>

{% endblock %}

{% block content %}
<div class="content">
    <div class="row">
        <div class="col-10">
            <div class='card'>
                <div class='card-body'>
                    <div class='row'>
                        <div class='col-6'>
                            <!-- Large modal -->

                            <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"
                                aria-labelledby="myLargeModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Create</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body" style='height:700px; overflow-y: scroll;'>
                                            <form method='post' class='form'
                                                action='{% url "notes:validate_note_creation" %}'>
                                                {% csrf_token %}
                                                {{ create_form }}
                                                <br />
                                                <button type='submit' class='btn btn-primary'><i class='fa fa-save'></i>
                                                    Save</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class='col-6 text-right'>

                        </div>
                    </div>
                    {% if q %}
                    <p>Search results for {{ q }}...</p>
                    {% endif %}

                    {% if qs and note_id or q %}
                    {% for note in qs %}
                    {% if q or note.id == note_id %}
                    {% include 'notes/note_card.html' %}
                    {% endif %}
                    {% endfor %}
                    {% else %}
                    No notes here. Please select a notebook tab on the left, or a note on the right.
                    {% endif %}


                </div>
            </div>
        </div>
        <div class="col-2">
            <div class='card'>
                <!-- { if user.is_authenticated } -->
                <button type="button" class="btn btn-success" data-toggle="modal" data-target=".bd-example-modal-lg">New
                    Note</button>
                <!-- { endif } -->

                {% if notebooktab_id %}
                {% for note in qs %}
                <a href="{% url 'notes:note' notebooktab_id note.id %}"><button type="button"
                        class="btn btn-active responsive-width"
                        style="padding: 2px; padding-left: {{ note.indent }}px; margin: 2px; text-align: left; width: 98%;">
                        {{ note.title }}
                    </button></a>
                {% endfor %}
                {% endif %}

            </div>
        </div>
    </div>

</div>



</div>

{% endblock %}

notebook/templates/notes/note_card.html
<div class='col-12'>
    <div class="card card-nav-tabs" style=' border-top: 5px solid {{ note.get_color_display }};'>
        <div class="card-header card-header-primary">
        </div>
        <div class="card-body">
            <h4 class="card-title">{{ note|safe }}</h4>

            <div class="clearfix">
                <p class='text-muted pull-left'>Created {{ note.created_timestamp}}</p>
                <p class='text-muted pull-right'>Modified {{ note.modified_timestamp}}
                </p>
            </div>


            <p class="card-text">{{ note.description|safe }}</p>
        </div>
        <div class="card-footer text-muted">
            <br>

            <a href='{{ note.get_edit_url }}' style='color:blue' class='pull-left'><i class='fa fa-edit'> </i></a>
            <a onclick='return confirm("Are you sure?")' href='{% url "notes:delete_note" note.id %}' style='color:red'
                class='pull-right'><i class='fa fa-trash'> </i></a>
        </div>
    </div>
</div>